-- MySQL Script generated by MySQL Workbench
-- 05/11/15 12:43:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema guessbid_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guessbid_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guessbid_db` DEFAULT CHARACTER SET latin1 ;
USE `guessbid_db` ;

-- -----------------------------------------------------
-- Table `guessbid_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guessbid_db`.`user` ;

CREATE TABLE IF NOT EXISTS `guessbid_db`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `credit` INT(10) UNSIGNED NOT NULL DEFAULT '100',
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `guessbid_db`.`bid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guessbid_db`.`bid` ;

CREATE TABLE IF NOT EXISTS `guessbid_db`.`bid` (
  `bid_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bidder_id` INT(11) NOT NULL,
  `bid_auction_id` INT(11) NOT NULL,
  `amount` FLOAT NOT NULL,
  PRIMARY KEY (`bid_id`),
  INDEX `bidder_id_idx` (`bidder_id` ASC),
  INDEX `bid_auction_id_idx` (`bid_auction_id` ASC),
  CONSTRAINT `bid_auction_id`
    FOREIGN KEY (`bid_auction_id`)
    REFERENCES `guessbid_db`.`auction` (`auction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bidder_id`
    FOREIGN KEY (`bidder_id`)
    REFERENCES `guessbid_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `guessbid_db`.`auction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guessbid_db`.`auction` ;

CREATE TABLE IF NOT EXISTS `guessbid_db`.`auction` (
  `auction_id` INT(11) NOT NULL AUTO_INCREMENT,
  `seller_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `end_time` DATETIME NOT NULL,
  `winning_bid_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`auction_id`),
  INDEX `seller_id_idx` (`seller_id` ASC),
  INDEX `winning_bid_id_idx` (`winning_bid_id` ASC),
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `guessbid_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `winning_bid_id`
    FOREIGN KEY (`winning_bid_id`)
    REFERENCES `guessbid_db`.`bid` (`bid_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `guessbid_db`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guessbid_db`.`notification` ;

CREATE TABLE IF NOT EXISTS `guessbid_db`.`notification` (
  `notification_id` INT(11) NOT NULL AUTO_INCREMENT,
  `n_user_id` INT(11) NOT NULL,
  `n_auction_id` INT(11) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `is_outcome` TINYINT(1) NOT NULL DEFAULT '0',
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_id`),
  INDEX `n_user_id_idx` (`n_user_id` ASC),
  INDEX `n_auction_id_idx` (`n_auction_id` ASC),
  CONSTRAINT `n_auction_id`
    FOREIGN KEY (`n_auction_id`)
    REFERENCES `guessbid_db`.`auction` (`auction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `n_user_id`
    FOREIGN KEY (`n_user_id`)
    REFERENCES `guessbid_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
